### ISSUE TITLE
Pretrained 모델 사용 규졍

### ISSUE THREAD

**Issue by dhkim2810** [DatathonInfo/MISOChallenge-musculoskeletal#13]
구체적인 pretrained 모델 샤용 규정이 있나요?

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

pretrained 모델 사용에 규정은 별도로 없으나, 
사용하시는 AI 모델(소스)이 타인의 저작권을 침해하면 안됩니다.

감사합니다.

**Comment by dhkim2810** [comment]
네. 감사합니다.
