### ISSUE TITLE
ModuleNotFoundError: No module named 'conda' 오류

### ISSUE THREAD

**Issue by dhkim2810** [DatathonInfo/MISOChallenge-musculoskeletal#7]
MISO충성충성팀입니다. 현재 사용하고 있는 서버 환경에서 conda 오류가 발생합니다.
자체적으로 조치하는 것보다 초기화해주시는게 빠를것 같아 이슈 남깁니다.

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

초기화 완료되었습니다.

감사합니다.
2021 미소 인공지능 모델 개발 첼린지 운영팀

**Comment by dhkim2810** [comment]
확인했습니다. 감사합니다.
